### ISSUE TITLE
Con Trai Lớn Quá Rồi <3, Bố cho tài liệu mà làm nè. Cố lên nhé con

### ISSUE THREAD

**Issue by nhattran998** [thaycacac/python-for-kids#1]
Link: [Sách Python For Kids](https://doc.lagout.org/programmation/python/Python%20for%20Kids_%20A%20Playful%20Introduction%20to%20Programming%20%5BBriggs%202012-12-22%5D.pdf)

**Comment by thaycacac** [comment]
Chỉ có thế là nhanh
